Download sources automatically and via pkgget

diff --git a/bin/pkgbuild b/bin/pkgbuild
--- a/bin/pkgbuild
+++ b/bin/pkgbuild
@@ -7,6 +7,12 @@ CURRENTDIR=`pwd`
 VERSION=`echo $VERSION_ID | sed -e 's/\..*//'`
 ARCH=`uname -m`
 
+if ! pkgget; then
+    echo
+    echo "Failed to build SRPM"
+    exit 255
+fi
+
 if ! rpmbuild -ba --define "_topdir $CURRENTDIR" --define "_builddir $CURRENTDIR/_workdir" $CURRENTDIR/SPECS/*.spec; then
     echo
     echo "Failed to build SRPM"
diff --git a/bin/pkgprep b/bin/pkgprep
--- a/bin/pkgprep
+++ b/bin/pkgprep
@@ -2,6 +2,12 @@
 
 CURRENTDIR=`pwd`
 
+if ! pkgget; then
+    echo
+    echo "Failed to build SRPM"
+    exit 255
+fi
+
 if ! rpmbuild -bp --nodeps --define "_topdir $CURRENTDIR" --define "_builddir $CURRENTDIR/_workdir" $CURRENTDIR/SPECS/*.spec; then
     echo
     echo "Failed to properly prep the RPM source tree"
